version: '3.1'

services:
  influxdb:
    container_name: influxdb
    environment:
      - INFLUXDB_DB=home
    image: hypriot/rpi-influxdb
    restart: always
    #volumes: ['/pirate/docker/influxdb:/var/lib/influxdb']
    ports : ['8086:8086']

  mqtt:
    container_name: mqtt
    image: elzekool/rpi-mosquitto
    restart: always
    ports : ['1883:1883']

  mongo:
    container_name: mongo
    image: andresvidal/rpi3-mongodb3:latest
    restart: always
    ports : ['28017:28017','27017:27017']
    environment:
      - MONGO_INITDB_DATABASE=home

  grafana:
    container_name: grafana
    image:  fg2it/grafana-armhf:v4.1.2
    restart: always
    #volumes: ['/pirate/docker/grafana:/var/lib/influxdb']
    ports : ['3000:3000']
