version: '3'
services:
  grafana:
    image: "fg2it/grafana-armhf:v4.1.2"
    ports:
     - "5000:3000"
    volumes:
     - /home/pi/iot/grafana:/var/lib/grafana
    depends_on:
      - influx
      - nodered
      - mqtt
    environment:
      - GF_PLUGIN_PATH = /var/lib/grafana/plugins
    links:
      - influx

  influx:
    image: "hypriot/rpi-influxdb"
    ports:
      - "5100:8086"
    volumes:
      - /home/pi/iot/influx:/data

  nodered:
    image: nodered/node-red-docker
    ports:
      - "5200:1880"
    volumes:
      - /home/pi/iot/nodered:/data
    links:
      - inlfux
      - mqtt

   mqtt:
     image: "pascaldevink/rpi-mosquitto"
     ports:
       - "5300:1883"
       - "5301:9001"
